### ISSUE TITLE
获取每个tableviewcell中图片的主颜色，如何处理更高效

### ISSUE THREAD

**Issue by wxzwork** [GodzzZZZ/MFExtractColor#1]
您好，看了一下您的这个三方，感觉很不错，但是想请问一下，如果说是想获取每个cell中图片的颜色，怎么样处理更高效一些呢？试了一下直接在cell中处理的话貌似有时候会取不到颜色，但是提前把颜色取出来放到cell的model数据中的话，由于取色是异步的，会比数据请求慢一些，感觉也不大合理，对此，有没有什么建议吗？
感谢！

**Comment by 1ess** [comment]
@wxzwork 
不好意思，刚看到。
正常来说，会出现取不到颜色的 BUG 吗？我记得之前的想法是把图片变成位图，计算权重来取出不同颜色。如果图片正常的话应该不会出现取不到的 BUG。
你说的这个情景我认为你说的图片是网络图片，直接在cell中处理是图片完成回调中对其颜色进行提取？那应当是没有问题，这也是一个比较好的处理位置。
如果还是出现你说的取不到颜色，你可以改进一下本库的算法，可以提 PR。
